name: Update Files on PRs

on:
  pull_request:
    types: 
      - opened

jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Files
        run: node src/generate-solidity.js && node src/generate-md.js
